### ISSUE TITLE
likelihood -> twoF conversion: missing factor of 2 for some diagnostic plots?

### ISSUE THREAD

**Issue by dbkeitel** [PyFstat/PyFstat#104]
@GregoryAshton in #103 I've introduced a new helper function `_get_twoF_from_loglikelihood()` to do the conversion
```
twoF = (self.lnlikes - self.likelihoodcoef) * 2
```
which was previously only done in `get_max_twoF()` without having to reproduce that somewhat arcane equation multiple times.

Doing so, I noticed two similar lines [here](https://github.com/PyFstat/PyFstat/blob/6143c992094fd30a32dee9a378e3919b440059bc/pyfstat/mcmc_based_searches.py#L1442) and [here](https://github.com/PyFstat/PyFstat/blob/6143c992094fd30a32dee9a378e3919b440059bc/pyfstat/mcmc_based_searches.py#L1456) which are however missing the factor of 2. They're only for diagnostic plots, but if you could confirm that they should have the 2, I'll fix them to use the helper function for consistency.

**Comment by GregoryAshton** [comment]
Yep looks like typo's to me!
