### ISSUE TITLE
Check plotting options...?

### ISSUE THREAD

**Issue by Rodrigo-Tenorio** [PyFstat/PyFstat#142]
As seen in #135 and #141 , plotting options should have a check done at some point.

Since most of them are basically used for diagnosis (as one would tailor a proper figure using the results), I'm hesitant to spend too much time in this issue.

@dbkeitel Opinion? This will probably become irrelevant if we ever interface Bilby.

**Comment by dbkeitel** [comment]
By "check" you mean adding calls to the test suite? Of course it's hard/impossible to automatically test if the plots are really sensible, but at least testing that they don't crash under various inputs would be good.

**Comment by Rodrigo-Tenorio** [comment]
Sort of  yes: If we include them into the test suite we will at least be aware of any breaking changes.

**Comment by dbkeitel** [comment]
Any PRs welcome, and we can also keep this open as a reminder issue for a good while.

I'll just adapt the labels so it doesn't sound like there's a specific known bug at the moment.

**Comment by dbkeitel** [comment]
Basic coverage should be there with #315 and #320 now. Any major ones I've missed @Rodrigo-Tenorio ?
