### ISSUE TITLE
Fix logging behaviour

### ISSUE THREAD

**Issue by Rodrigo-Tenorio** [PyFstat/PyFstat#163]
There are at least two known issues related to logging and PyFstat:

- [ ] Logging messages appear twice when run under GitHub's CI (and containers as well!)
- [ ] Logging output goes to STDERR rather than STDOUT

Not a high priority issue: Any error worth of going into STDERR will terminate the job, although it would be worth knowing why this happens.

**Comment by dbkeitel** [comment]
- [ ] each Writer / search class should self-identify in the log at init time. Currently the first message from each class is often something very random like band estimation. (I'm planning to do this one quickly after the current bugfix PRs are in.)

**Comment by dbkeitel** [comment]
Regarding duplicate logging: This also happens for me with pytest locally.

Regarding stderr vs stdout:

- from https://docs.python.org/3/howto/logging.html :
> By default, no destination is set for any logging messages. You can specify a destination (such as console or file) by using basicConfig() as in the tutorial examples. If you call the functions debug(), info(), warning(), error() and critical(), they will check to see if no destination is set; and if one is not set, they will set a destination of the console (sys.stderr) and a default format for the displayed message before delegating to the root logger to do the actual message output.

- https://stackoverflow.com/questions/16061641/python-logging-split-between-stdout-and-stderr
- https://stackoverflow.com/questions/2302315/how-can-info-and-debug-logging-message-be-sent-to-stdout-and-higher-level-messag

**Comment by Rodrigo-Tenorio** [comment]
>     * [ ]  each Writer / search class should self-identify in the log at init time. Currently the first message from each class is often something very random like band estimation. (I'm planning to do this one quickly after the current bugfix PRs are in.)

Regarding this, I'm sure we can just add something fancy using `self.__name__` in `BaseSearchClass` which gets automatically inherited by everyone else (since I'd say everything inherits from`BaseSearchClass` in the end).

**Comment by Rodrigo-Tenorio** [comment]
[According to logging's documentation](https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library) it's the application, rather than the library, the ultimate responsible to take care of logging.
