### ISSUE TITLE
uniform prior sometimes not shown correctly in plot_prior_posterior()

### ISSUE THREAD

**Issue by dbkeitel** [PyFstat/PyFstat#164]
While checking all example figures from #159 / [run 246925595](https://github.com/PyFstat/PyFstat/actions/runs/246925595), I noticed that the `prior_posterior` plots sometimes look odd, with the horizontal line for a uniform prior drawn at the bottom instead of the top. This seems to happen for the binary and the transient example:

![PyFstat_example_semi_coherent_binary_search_using_MCMC_prior_posterior](https://user-images.githubusercontent.com/28396587/92704296-25c93580-f353-11ea-9048-d9a8872cbf41.png)

![transient_search_prior_posterior](https://user-images.githubusercontent.com/28396587/92704338-2d88da00-f353-11ea-843b-29b3d511af4a.png)

**Comment by Rodrigo-Tenorio** [comment]
I made a mistake and solved this issue in #172 ...

**Comment by Rodrigo-Tenorio** [comment]
Closed by #173
