### ISSUE TITLE
MCMC walker plots: injection parameter not properly scaled

### ISSUE THREAD

**Issue by dbkeitel** [PyFstat/PyFstat#166]
When doing `mcmc.run(walker_plot_args={"plot_det_stat": True, "injection_parameters": inj})` on a `MCMCTransientSearch` object, the injected start/duration parameters are not rescaled and hence the plot looks completely off:

![transient_search_walkers](https://user-images.githubusercontent.com/28396587/92725233-1d312900-f36c-11ea-9ea1-0e9a75cde8b0.png)

The `transform_dictionary` is set up properly and `MCMCSearch._plot_walkers()` (which is inherited unmodified) does have a `_scale_samples()` call, so I'm not sure yet where the crucial info gets lost - probably a parameter name inconsistency somewhere.

**Comment by dbkeitel** [comment]
The same actually happens for standard MCMC when setting a custom `transform_dictionary` as done e.g. in `PyFstat_example_fully_coherent_MCMC_search.py` and I think it affects corners as well. The problem is that the `transform_dictionary` is just not consulted for the `truths`/`injection_parameters`.

**Comment by dbkeitel** [comment]
@Rodrigo-Tenorio would you have a chance to look into the walker plot maybe? I've started a branch and PR in #172 exposing the issue on the simple fully_coherent example.

**Comment by Rodrigo-Tenorio** [comment]
Sure, I remember seeing that `scale_samples` option when I re-implemented the `truths` argument, seems I overlooked it in the end.

**Comment by dbkeitel** [comment]
On the corner plots, I think I was just confused looking at e.g. this output of `examples/mcmc_examples/PyFstat_example_fully_coherent_MCMC_search.py` which looks a bit off, but notice it's nanoHertz and 10^-15 spindown, so actually fine.

![PyFstat_example_fully_coherent_MCMC_search_corner](https://user-images.githubusercontent.com/28396587/93303938-8695b980-f7fc-11ea-88cb-39e3cef6abca.png)
