### ISSUE TITLE
check on PyFstat_example_twoF_cumulative.py

### ISSUE THREAD

**Issue by dbkeitel** [PyFstat/PyFstat#170]
I'm not actually sure what this example is supposed to be achieving, but this plot doesn't look like an intended result any more:

![PyFstat_example_twoF_cumulative_twoFcumulative](https://user-images.githubusercontent.com/28396587/93216507-1f2e2a00-f768-11ea-9cbe-bf4d4752dea5.png)

**Comment by Rodrigo-Tenorio** [comment]
The examples uses `plot_cumulative_max`, which falls back to some sort of `calculate_twoF_cumulative` in the base search class.

**Comment by dbkeitel** [comment]
Going back to v.1.5.0 tag:

![PyFstat_example_twoF_cumulative_twoFcumulative](https://user-images.githubusercontent.com/28396587/93779425-4339b180-fc27-11ea-89a0-0f45001e93b9.png)

**Comment by Rodrigo-Tenorio** [comment]
I get using 7112bca1aa2252dde25afd616b290927d0799fe2
![2Ftrial](https://user-images.githubusercontent.com/49152330/93782836-4fc00900-fc2b-11ea-903b-533bdb27c351.png)
Maybe the signal is too weak? Anyways, this is a starting point.

**Comment by Rodrigo-Tenorio** [comment]
Solved in  c63c4ac .

**Comment by dbkeitel** [comment]
This was broken since almost 3 years, as in 73fee7871018e72ed6ba965d8cae343ebc89f8a8 I blindly replaced some `transientWindowType`s without understanding what this function actually does. :crying_cat_face:

**Comment by Rodrigo-Tenorio** [comment]
MultiIFO example of the latest version (this is still `ComputeFstat`)
![PyFstat_example_twoF_cumulative_twoFcumulative](https://user-images.githubusercontent.com/49152330/93793049-9bc47b00-fc36-11ea-8239-14d363007375.png)

**Comment by Rodrigo-Tenorio** [comment]
Let's include some backwards-incompatible ugly-(but maybe useful)-looking PFS plots, shall we?
![PyFstat_example_twoF_cumulative_twoFcumulative](https://user-images.githubusercontent.com/49152330/93800516-fcf14c00-fc40-11ea-975f-beacca2b90db.png)

**Comment by Rodrigo-Tenorio** [comment]
I just realizeed that band should as well be growing with time.

**Comment by dbkeitel** [comment]
Yes, the behaviour of the PredictFstat outputs actually seemed correct in the 1.5.0 example above.

**Comment by dbkeitel** [comment]
Solved in #186.
