### ISSUE TITLE
axis label auto-scaling issues

### ISSUE THREAD

**Issue by dbkeitel** [PyFstat/PyFstat#184]
Known issue: axis labels on corner plots often become unreadable, especially for frequencies with many post-decimal digits. Also affects the recently revived (#183) "chainconsumer" plots.

Since we don't necessarily promise publication-ready plots, this isn't high priority to address.

**Comment by dbkeitel** [comment]
@Rodrigo-Tenorio are we happy enough with the current (vastly improved) state?

**Comment by Rodrigo-Tenorio** [comment]
There's still one last thing I'd like to have a look at: Adjust the format of title values (the ones shown at the top of each histogram) not to show 0.00 +- 0.00 whenever values are too small.
