### ISSUE TITLE
Deprecate and then remove various special classes

### ISSUE THREAD

**Issue by dbkeitel** [PyFstat/PyFstat#213]
Hi @ReinhardPrix : Given that @GregoryAshton has almost no time left to maintain any parts of this package and @Rodrigo-Tenorio and I can only effectively maintain the parts we're actively using, we have decided we'd like to remove various specialised classes, all from the grid_based_searches.py module, to make it easier to do some other necessary internal changes. These classes have so far been kept technically alive (tests pass where they exist), but we haven't checked in detail in a long time if they really still do what they're supposed to (and not in all cases do I even really know what they're supposed to do), and some don't have tests at all.

Specifically, these classes are:
 - SliceGridSearch
 - GridUniformPriorSearch
 - SlidingWindow
 - FrequencySlidingWindow
 - EarthTest
 - DMoff_NO_SPIN

I'll do a first PR shortly to _**deprecate**_ them and we'll include that already in an imminent 1.9.0 release. Then I'll make a separate PR for _**removing**_ them and assign that one to you; then it would be great if you can reply, by sometime next week, whether you are still interested in using any subset of them, and we would then keep those and try together to make sure they're correct and properly tested.

**Comment by ReinhardPrix** [comment]
David, thanks for the heads up. Please go ahead, you're clearly the main users and developers of this right now, so I have no objections if you want to do some cleanup / simplifications. There's always git-history and clones anyway, so no worries.

**Comment by dbkeitel** [comment]
Thanks for the quick feedback! If you ever find you need one of those classes, let us know.
