### ISSUE TITLE
Enhance injection options

### ISSUE THREAD

**Issue by Rodrigo-Tenorio** [PyFstat/PyFstat#40]
Actually, `get_covering_band()` doesn't seem to be in use either...

@GregoryAshton Do you remember what was the intended use of the homebrew `get_frequency_range_of_signal()` and the whole `injection_helper_functions.py` module? I agree with @Rodrigo-Tenorio that this looks like it could just be removed at this point.

_Originally posted by @dbkeitel in https://github.com/PyFstat/PyFstat/pull/38#issuecomment-612122286_

I'd keep `get_frequency_range_of_signal()`. I myself have coded some similar functions whenever I had to do injections and this one will come handy.

I would let the user decide whether they want to use it or on the other hand they want to write a particular band by themselves (makefakedata_v5 will complain if the band is not wide enough).

On the other hand Makefakedata's `--noiseSFTs` could  be implemented to allow for injections using SFTs noise rather than just gaussian noise.

**Comment by dbkeitel** [comment]
In #49 I now have repurposed `get_covering_band()` for internal use, so that one will definitely stay.

**Comment by dbkeitel** [comment]
Remaining changes will be done in #41.

**Comment by dbkeitel** [comment]
Effectively done with #41, just need to decide on #38, but no need for this issue any more.
