### ISSUE TITLE
Zenodo URL correct?

### ISSUE THREAD

**Issue by ReinhardPrix** [PyFstat/PyFstat#42]
Hi guys, I'm a bit puzzled by the quoted zenodo URL in the README, which is
https://doi.org/10.5281/zenodo.3620860
which brings me to this page
https://zenodo.org/record/3620860
with title "Dataset for INTEGRACE VÝROBEN S U/Q REGULACÍ DO DISTRIBUČNÍCH SÍTÍ VN
Švec, Jan; Kůla, Jan; Derner, Pavel; Hes, Stanislav"

.. is that a temporary DOI problem or is there something wrong with that DOI link?

**Comment by ReinhardPrix** [comment]
ok, quick search on zenodo shows this to be the most recent URL that looks correct (version 1.3)?
https://zenodo.org/record/3620861
seems to be off by one in fact ... ?!

**Comment by dbkeitel** [comment]
Good catch. The direct Zenodo links in the README are correct, but I somehow got the DOI wrong. There's several ways to refer to either a specific version, or the general version-independent entry:

- v1.3: https://doi.org/10.5281/zenodo.3620861 or https://zenodo.org/record/3620861
- version-independent: https://doi.org/10.5281/zenodo.1243930 or https://zenodo.org/record/1243930

All 4 currently should take you to https://zenodo.org/record/3620861 in the end, but the latter two will redirect once there is a v1.4.
