### ISSUE TITLE
black vs tutorial notebooks

### ISSUE THREAD

**Issue by dbkeitel** [PyFstat/PyFstat#421]
@Rodrigo-Tenorio just noticed that a top-level `black .` will modify the notebooks in `examples/tutorials`. Questions:

- [x] can you confirm whether they'd be screwed up by that or if it's safe?
- [x] do you remember where they are explicitly, or implicitly, excluded from the standard black hooks?

**Comment by Rodrigo-Tenorio** [comment]
> do you remember where they are explicitly, or implicitly, excluded from the standard black hooks?

There's apparently an extra hook for jupyter notebooks:
https://github.com/psf/black/blob/main/.pre-commit-hooks.yaml

Implemented in #429
