### ISSUE TITLE
check mistune pin

### ISSUE THREAD

**Issue by dbkeitel** [PyFstat/PyFstat#446]
We were on "<2.0.0" since https://github.com/PyFstat/PyFstat/pull/360 and now #435 changes it to "==0.8.4" which happents to be equivalent as per
https://pypi.org/project/mistune/#history

But they're now at 2.0.4 stable and 3.0.0 alpha, so we should check what's going on with cross-dependencies.

**Comment by Rodrigo-Tenorio** [comment]
For the record: I unpinned everything in docs and let pip decide on the proper combination.
I may have missed that one as well, but that's what I intended to do.

**Comment by dbkeitel** [comment]
This is still the version one ends up when unpinning and letting sphinx & friends do their thing. It actually comes in via `m2r2` and removing that pin is a long-standing work-in-progress of theirs tracked here: https://github.com/CrossNox/m2r2/issues/47

Nothing for us to do.
