### ISSUE TITLE
tqdm vs logging

### ISSUE THREAD

**Issue by dbkeitel** [PyFstat/PyFstat#449]
Another followup from #435 : it seems the tqdm capture doesn't really work. E.g. if I do
```
logger = pyfstat.set_up_logger(label=label, outdir=outdir)
for handler in logger.handlers:
    if type(handler) == logging.StreamHandler:
        logger.removeHandler(handler)
```
at the start of any grid/mcmc search example, which should then send no logging info to stdout but only to the file, I still get the progress bar on the terminal, and none of it in the file.

On the one hand, a progress bar obviously makes more sense on stdout than in a file, so maybe this is just what tqdm wants to keep doing and can't be persuaded otherwise, which I could live with. On the other hand, it seems like the `logging_redirect_tqdm` is supposed to change this, so it'd be good to check why it doesn't/

**Comment by Rodrigo-Tenorio** [comment]
From [the docs](https://tqdm.github.io/docs/contrib.logging/):
> Context manager redirecting console logging to tqdm.write(), leaving other logging handlers (e.g. log files) unaffected.

Do I interpret correctly that `tqdm` output is simply not handled by logger at all, and this only makes sure that, in case you redirected anything, tqdm doesn't get redirected and still prints to stdout?

If so, #449.

**Comment by Rodrigo-Tenorio** [comment]
Relevant thread: https://github.com/tqdm/tqdm/issues/313
