### ISSUE TITLE
Rename `pyfstat.logging` to `pyfstat.log` to avoid name clashing

### ISSUE THREAD

**Issue by Rodrigo-Tenorio** [PyFstat/PyFstat#460]
PyFstat's `logging` module name-clashes with Python's `logging` module, making modules unable to be run as scripts.

PR incoming once network allows me to push.

**Comment by dbkeitel** [comment]
@Rodrigo-Tenorio any followup on a case where this actually causes a conflict? Since as far as I know, we never (recommend to) do `from pyfstat import logging`.
