### ISSUE TITLE
Tukey window does not require beta parameter

### ISSUE THREAD

**Issue by Rodrigo-Tenorio** [PyFstat/PyFstat#474]
Once LALSuite's [614](https://git.ligo.org/lscsoft/lalsuite/-/issues/614) is fixed, we should patch PyFstat so tukey beta=0 is not given by default and LALSuite is able to catch whether the user forgot.

**Comment by dbkeitel** [comment]
This was already done back in 954ddb80e48e124f3f1f8c0530bcde88b16e3d1f
