### ISSUE TITLE
Could not find either lalpulsar or lalapps version of command Makefakedata_v5

### ISSUE THREAD

**Issue by ghost** [PyFstat/PyFstat#475]
I've created a virtual environment installed pyfstat with `pip install pyfstat`.
I use pip version 22.2.2 with python 3.8
when executing `import pyfstat`  in a jupyter notebook I receive the following error

![image](https://user-images.githubusercontent.com/61739497/195857640-d051987f-ef03-49dd-a8f6-8e365876bef6.png)

When i execute `import pyfstat` through a command line i don't receive an error.

I always receive following warning
![image](https://user-images.githubusercontent.com/61739497/195858163-e71c0eb8-2c53-4dcc-b02b-a3517691084d.png)

**Comment by Rodrigo-Tenorio** [comment]
Hi @adr433 , thanks for reporting.

Could you please paste here the output of `pip list` inside your environment?

Also, how did you create your environment?

**Comment by adr433** [comment]
I used `python -m virtualenv env_kaggle` to create my virtualenv.
This is the output of `pip list`  => [output.txt](https://github.com/PyFstat/PyFstat/files/9786953/output.txt)
running lalpulsar version in notebook and command line both gives me '5.1.1.1'

**Comment by Rodrigo-Tenorio** [comment]
@adr433 

Cool, another thing I forgot: What OS are you using?

**Comment by Rodrigo-Tenorio** [comment]
I just tried to install PyFstat in a conda environment with python 3.8 and pip 22.2.2 and cannot reproduce the error.

I noticed, however, that you don't seem to have some of the following jupyter packages in your environment
```
jupyter              1.0.0
jupyter_client       7.4.2
jupyter-console      6.4.4
jupyter-core         4.11.1
jupyter-server       1.21.0
jupyterlab-pygments  0.2.2
jupyterlab-widgets   3.0.3
```

How did you install `jupyter`? Did you run `pip install jupyter` in the environment and then `jupyter notebook`?

**Comment by dbkeitel** [comment]
Thanks for reporting the problem. To make sure jupyter sees all dependencies, I also usually do `ipython kernel install --user --name=NAMEOFVENV` and then choose that kernel from the notebook (see https://anbasile.github.io/programming/2017/06/25/jupyter-venv/ ).

But independent of that, it's very odd that you got the `lalsuite          7.10.1.dev20221014 ` dependency version installed. Normally `dev` versions should only ever get pulled in if you use `pip install --pre`. Do you get the same version if you create another fresh environment and in that one just do `pip install lalsuite` directly? If yes, that seems like a problem to report upstream for LALSuite..

**Comment by adr433** [comment]
Hi,
Thanks for the quick responses. Some more information.

> **How did you install jupyter? Did you run pip install jupyter in the environment and then jupyter notebook?**
I'm using a notebook server on a private machine so some of the packages might be missing. 
see also: https://jupyter-notebook.readthedocs.io/en/stable/public_server.html#

> **To make sure jupyter sees all dependencies, I also usually do ipython kernel install --user --name=NAMEOFVENV**
I've installed using `python -m ipykernel install` and `ipython kernel install` both give me a kernel but give the same runtime error as above

> **Do you get the same version if you create another fresh environment and in that one just do pip install lalsuite directly?**
I've installed lalsuite directly as first package using `pip install lalsuite`. These are my installed packages
[output (2).txt](https://github.com/PyFstat/PyFstat/files/9798202/output.2.txt)
output of `pip show lalsuite`
[lalsuite.txt](https://github.com/PyFstat/PyFstat/files/9798257/lalsuite.txt)

> **I just tried to install PyFstat in a conda environment with python 3.8 and pip 22.2.2 and cannot reproduce the error.**
I'm using python version 3.8.15, Ubuntu 18.04.6 LTS, gcc version 7.5
I used the command `python -m virtualenv env_kaggle` to make a virtual environment.

I can also try to work on a different machine/environment

**Comment by Rodrigo-Tenorio** [comment]
Hi @adr433 , 

Thanks for the answer. 

So, I think the problem goes as follows: When you install `lalsuite` using `pip`, you get a "standard" Python package (i.e. functions you can import) plus a set of *executables* which get pulled into your environment (e.g. `lalpulsar_Makefakedatav5`). 

For some reason, those executables don't get included into your environment, hence PyFstat complains.

Just to be sure: Have you restarted your jupyter server lately?

> I can also try to work on a different machine/environment

If that is possible, I'd suggest you to try and see if the standard way of installing (create a venv, pip install) works for you.

**Comment by Rodrigo-Tenorio** [comment]
Closing due to lack of response, happy to open again if the issue persists :)
