### ISSUE TITLE
".pystat.conf. file is missing", pip version: 3.10., pyfstat version: 1.181. , LALsuite version: 7.10.

### ISSUE THREAD

**Issue by bhaskar-verma** [PyFstat/PyFstat#478]
**Describe the bug**

**Expected behavior**
If possible, summarize the intended behavior you expected to get.

**Environment (please complete the following information):**
- What OS are you using?
- What sort of virtual environment (if any) are you using? How did you create it? Please attach command if possible.
- Please attach output of `pip list`, `conda list` or equivalent.
- How did you install PyFstat? Please attach command if possible.

**To Reproduce**
Steps to reproduce the behavior. Please be as specific as possible.
The more you tell us about what you did, the easier it will be to get it fixed :) .

**Additional context**

**Comment by Rodrigo-Tenorio** [comment]
Hi @bhaskar-verma , sorry for the late response.

Do I understand correctly that you *only* ran `conda install -c conda-forge pyfstat jupyter`? 
Have you, at any point, run `pip install lalsuite` on that very same environment?

**Comment by bhaskar-verma** [comment]
Hey Rodrigo,

I have run both of those commands on the very same environment.


________________________________

**Comment by Rodrigo-Tenorio** [comment]
Hi @bhaskar-verma ,

Cool, could you create a brand new environment and then only run `conda install -c conda-forge pyfstat jupyter`?

**Comment by Rodrigo-Tenorio** [comment]
Closing due to lack of response, happy to open up again if the issue persists :)
