### ISSUE TITLE
segmentation fault from BSGL grid test with recent LALSuite nightlies

### ISSUE THREAD

**Issue by dbkeitel** [PyFstat/PyFstat#488]
**Describe the bug**
see https://github.com/PyFstat/PyFstat/actions/runs/3360239212/jobs/5569188206#step:7:104

The first failing version seems to be `7.10.1.dev20221025`.

Note that the non-BSGL `TestGridSearch::test_semicoherent_grid_search` does **not** segfault.

**Expected behavior**
no segfault

**Environment (please complete the following information):**
- see action setup, but can aso reproduce locally

**To Reproduce**
```
pip install --upgrade --pre lalsuite==7.10.1.dev20221025
pytest tests/test_grid_based_searches.py::TestGridSearchBSGL::test_semicoherent_grid_search
```

**Additional context**
---

**Comment by dbkeitel** [comment]
Seems like https://git.ligo.org/lscsoft/lalsuite/-/merge_requests/2024 was the relevant lalsuite MR (not a big surprise), but what surprises me is that it's a harmless-seeming call `lalpulsar.CreateMultiFstatAtomVector(1)` that seems to be failing. I'll try to isolate a minimal test case...

**Comment by dbkeitel** [comment]
Unfortunately I was not able yet to construct a PyFstat-free simplified test case for cleanly reporting upstream. This is how far I've got with our machinery:

So the line that the trace from `pytest` points to is https://github.com/PyFstat/PyFstat/blob/master/pyfstat/core.py#L1995 (which, as per above, is when we call `lalpulsar.CreateMultiFstatAtomVector`) but when I run a simplified reproduction test case (see end of post, can't attach) through
```
gdb python
run test_segfault_pyfstat.py
backtrace
```
then it actually points to `XLALDestroyMultiFstatAtomVector` as the culprit.

I've also added debug statements inside the grid search `run()` loop and the `get_semicoherent_single_IFO_twoFs()` method, which tells me that the problem happens at some point during **repeat** calls of that method: via pytest it seems to (reproducably on my setup) happen at the n=3, X=1 (4th freq bin, 2nd detector) while with the standalone script the freq bin randomly varies but always 2nd detector too.

In both the unit test and my standalone script, the logic is an outer loop over frequency bins and an inner one over detectors, re-creating the `singleIFOmultiFatoms` at each pass through the inner loop. So I'd say something goes wrong with the ownership of that object's memory, so that throughout the loops, sometimes python decides to garbage-collect and destroy it, sometimes it doesn't; and then re-creating it triggers a destruction which will fail or not depending on that unpredictable state.

Standalone test:
```
import logging
import pyfstat

logging.getLogger('pyfstat').setLevel(logging.DEBUG)

outdir = "TestData"

Writer_params = {
    "label": "test",
    "sqrtSX": 1,
    "Tsft": 1800,
    "tstart": 700000000,
    "duration": 4 * 1800,
    "detectors": "H1,L1",
    "SFTWindowType": "tukey",
    "SFTWindowBeta": 0.001,
    "randSeed": 42,
    "Band": 0.5,
}

signal_params = {
    "F0": 30.0,
    "F1": -1e-10,
    "F2": 0,
    "h0": 5.0,
    "cosi": 0,
    "psi": 0,
    "phi": 0,
    "Alpha": 5e-1,
    "Delta": 1.2,
}

Writer = pyfstat.Writer(
    outdir=outdir,
    **Writer_params,
    tref=Writer_params["tstart"],
    **signal_params,
)
Writer.make_data()

F0s = [29.999, 30.001, 1e-4]

search = pyfstat.GridSearch(
    "sc_grid_search",
    Writer.outdir,
    Writer.sftfilepath,
    F0s=F0s,
    F1s=[Writer.F1],
    F2s=[Writer.F2],
    Alphas=[Writer.Alpha],
    Deltas=[Writer.Delta],
    tref=Writer_params["tstart"],
    nsegs=2,
    BSGL=True,
)
search.run()
```

**Comment by kwwette** [comment]
@dbkeitel I think what's happening in [this line](https://github.com/PyFstat/PyFstat/blob/c502303284fc4fba4dbe34eee1063d0f75d8b7e5/pyfstat/core.py#L2001):
```
singleIFOmultiFatoms.data[0].data = self.FstatResults.multiFatoms[0].data[X].data
```
is that `singleIFOmultiFatoms` is taking ownership of the memory in `self.FstatResults.multiFatoms[0].data[X].data` which is ultimately owned by `self.FstatResults`. So if both `singleIFOmultiFatoms` and `self.FstatResults` get destroyed, you will get a segfault.

As a general rule, assigning SWIG-wrapped pointers to SWIG-wrapped struct fields / array elements transfers memory ownership to the assigned-to struct / array. This follows the usual way LAL destructors are written, where a struct destroys not only its own memory but also any memory it points to. You'd have the same problem if you wrote the same code in C and then called both `XLALDestroyMultiFstatAtomVector()` and `XLALDestroyFstatResults()`.

I'm not sure why this was working before; often such memory issues can remain undiagnosed if the memory still remains available, but perhaps the recent SWIG changes have now exposed the underlying bug.

I think you can fix this by doing the following, after calling `lalpulsar.ComputeTransientFstatMap()`:
```
singleIFOmultiFatoms.data[0].data[0] = lalpulsar.FstatAtom()
```
This assigns a freshly created `FstatAtom()` to the array, which can then should be safely destroyed when `singleIFOmultiFatoms` is destroyed, without also destroying any data from `self.FstatResults`.

**Comment by dbkeitel** [comment]
Thanks a lot @kwwette you've definitely identified where exactly the problem happens: if I replace that data assignment line with a manual deep copy, the segfault disappears.

Your more elegant workaround _sounds_ like it should help, but unfortunately it doesn't - and neither does this looped version I've also tried:
```
            for k in range(singleIFOmultiFatoms.data[0].length):
                singleIFOmultiFatoms.data[0].data[k] = lalpulsar.FstatAtom()
```
I'd say this seems like the transferred ownership is not transferred back to `self.FstatResults` on assigning something new to `singleIFOmultiFatoms`, and hence garbage collection can still destroy the original atoms if we're unlucky.

I'll time the hardcopy version and see if we can live with that for now (the BSGL/single-IFO version hasn't really been used for anything production-level anyway), or else think harder about a nicer solution.

**Comment by dbkeitel** [comment]
Timing impact of deepcopy seems to be negligible -> #489 unless someone has a smarter idea

**Comment by kwwette** [comment]
It looks like `FstatAtomVector` is a pointer-to-structs type array, i.e. the `data` memory is the actual `FstatAtom` struct in memory, one element after another, rather than pointers to `FstatAtom`. Assigning to the `data` memory may be assigning the array memory rather than making a copy. So it any case it looks like you'd have to copy the data anyway, so just doing a `deepcopy` seems fine.
