### ISSUE TITLE
<jupyter lab >RuntimeError: Could not find either lalpulsar or lalapps version of command Makefakedata_v5.

### ISSUE THREAD

**Issue by kof8855** [PyFstat/PyFstat#500]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In [16], line 1
----> 1 import pyfstat

File /usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/pyfstat/__init__.py:37
     32 from .gridcorner import gridcorner
     33 from .injection_parameters import (
     34     AllSkyInjectionParametersGenerator,
     35     InjectionParametersGenerator,
     36 )
---> 37 from .make_sfts import (
     38     BinaryModulatedWriter,
     39     FrequencyAmplitudeModulatedArtifactWriter,
     40     FrequencyModulatedArtifactWriter,
     41     GlitchWriter,
     42     LineWriter,
     43     Writer,
     44 )
     45 from .mcmc_based_searches import (
     46     MCMCFollowUpSearch,
     47     MCMCGlitchSearch,
   (...)
     50     MCMCTransientSearch,
     51 )
     52 from .snr import DetectorStates, SignalToNoiseRatio

File /usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/pyfstat/make_sfts.py:21
     16 from pyfstat.core import BaseSearchClass, SearchForSignalWithJumps
     18 logger = logging.getLogger(__name__)
---> 21 class Writer(BaseSearchClass):
     22     """The main class for generating data in the form of SFTs.
     23 
     24     Short Fourier Transforms (SFTs) are a standard data format used in LALSuite,
   (...)
     35     for more detailed help with some of the parameters.
     36     """
     38     mfd = utils.get_lal_exec("Makefakedata_v5")

File /usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/pyfstat/make_sfts.py:38, in Writer()
     21 class Writer(BaseSearchClass):
     22     """The main class for generating data in the form of SFTs.
     23 
     24     Short Fourier Transforms (SFTs) are a standard data format used in LALSuite,
   (...)
     35     for more detailed help with some of the parameters.
     36     """
---> 38     mfd = utils.get_lal_exec("Makefakedata_v5")
     39     """The executable; can be overridden by child classes."""
     41     signal_parameter_labels = [
     42         "tref",
     43         "F0",
   (...)
     54         "transientTau",
     55     ]

File /usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/pyfstat/utils/runlalsuite.py:35, in get_lal_exec(cmd)
     33 full_cmd = shutil.which("lalpulsar_" + cmd) or shutil.which("lalapps_" + cmd)
     34 if full_cmd is None:
---> 35     raise RuntimeError(
     36         f"Could not find either lalpulsar or lalapps version of command {cmd}."
     37     )
     38 return os.path.basename(full_cmd)

RuntimeError: Could not find either lalpulsar or lalapps version of command Makefakedata_v5.

**Comment by dbkeitel** [comment]
@kof8855 we've dug a bit deeper and written up our recommendations at https://github.com/PyFstat/PyFstat/wiki/conda-environments#enabling-jupyter-notebooks

Let us know if that resolves it.

**Comment by kof8855** [comment]
> @kof8855 we've dug a bit deeper and written up our recommendations at https://github.com/PyFstat/PyFstat/wiki/conda-environments#enabling-jupyter-notebooks
> 
> Let us know if that resolves it.


thanks，done


import os
import sys
env_bin = os.path.dirname(sys.executable)
if not env_bin in os.environ["PATH"]:
    os.environ["PATH"] = f'{env_bin}:{os.environ["PATH"]}'
import pyfstat

**Comment by dbkeitel** [comment]
Ok, good! It'll be a bit annoying to have to do that every time, but for now it seems it's just a limitation of jupyter kernels.  There might be some smart way to modify the kernelspec file to do something similar automatically - see the issue linked from the wiki -  but I haven't looked into it further.

Is this ok to close then?

**Comment by kof8855** [comment]
> Ok, good! It'll be a bit annoying to have to do that every time, but for now it seems it's just a limitation of jupyter kernels. There might be some smart way to modify the kernelspec file to do something similar automatically - see the issue linked from the wiki - but I haven't looked into it further.
> 
> Is this ok to close then?

ok
