### ISSUE TITLE
no ephemerides in docker container

### ISSUE THREAD

**Issue by dbkeitel** [PyFstat/PyFstat#74]
@Rodrigo-Tenorio it looks like the docker container is not actually very useful yet as it doesn't contain ephemerides files. Do you think there's an easy way to do a download like this: https://github.com/PyFstat/PyFstat#ephemerides-installation from the Dockerfile that builds the image, or does that build action not have internet access and we need local copies of them?

Alternatively, we could have a helper function that downloads them on-the-fly, but I think there will likely be use-cases on non-LDG clusters where you want to use Docker but don't have outgoing internet access from worker nodes.

**Comment by Rodrigo-Tenorio** [comment]
@dbkeitel Yes, builds are (or should be) able to get stuff from the internet (e.g. the `pip install -r requirements.txt` needs internet acces). I'll probably add those instructions you just linked to the Dockerfile and that's it.

Question: How difficult is it to include those ephemeris in the package itself or to tell pip to download them? Do you know about the pythonic way of doing this?

**Comment by dbkeitel** [comment]
> I'll probably add those instructions you just linked to the Dockerfile and that's it.

If it can just run wget, that's the easiest way to get them. The tricky part is knowing what's a good local location inside the image to put them into and point the env variable to - but maybe if you know more about their internal structure than me (i.e. more than 0) it's not actually tricky. ;)

> How difficult is it to include those ephemeris in the package itself

I'd like to avoid that (data duplication).

>  or to tell pip to download them

Probably not pip, but may be possible in setup.py.

See also https://git.ligo.org/lscsoft/lalsuite/-/issues/326 for earlier discussion of how to resolve this on the LALSuite side.

Follow-up question for you: do you ever need ephemerides other than DE405?

**Comment by dbkeitel** [comment]
Indeed after #75 was merged to master and the c7bc7fc6 image built by github, I can successfully run examples with it. Thanks Rodrigo!
