### ISSUE TITLE
v.1.4.* Zenodo releases

### ISSUE THREAD

**Issue by dbkeitel** [PyFstat/PyFstat#81]
@GregoryAshton while I can do the arguably more useful PyPi releases now, you'll still need to do the Zenodo source releases unless we find a way to add co-maintainers there.

Can you please also include Rodrigo in the author meta data with the following ORCID:
https://orcid.org/0000-0002-3582-2587

**Comment by dbkeitel** [comment]
Actually there is now a 1.4.1 already since @Rodrigo-Tenorio found another small bug he needed urgently fixed.

@GregoryAshton how much work is each Zenodo release, do you just want do both or is it better to skip 1.4.0 over there?

We should probably also look into automating this part, have you done so for bilby or other projects before?

**Comment by GregoryAshton** [comment]
@dbkeitel I created 1.4.1 here: https://zenodo.org/record/3964988#.XyCld3UzakA

I agree this needs automation - or co-management. When you login in to zenodo (with your orcid) and head to the pyfstat page, do you see a "new version" button?

**Comment by dbkeitel** [comment]
From 1.5 on, releases should hopefully get automatically picked up by Zenodo now that I've linked the accounts. The "all versions" DOI may change though since I found no way to link it to the old listing. Let's see what happens, and amend the README citation guidelines correspondingly.
