### ISSUE TITLE
Improve handling of timestamps when noiseSFTs is present

### ISSUE THREAD

**Issue by Rodrigo-Tenorio** [PyFstat/PyFstat#84]
Currently, [Writer](https://github.com/PyFstat/PyFstat/blob/master/pyfstat/make_sfts.py#L27) accepts `noiseSFTs` as a way of adding noise to the injections; however, timestamp information (such as time start, duration and so on) still has to be given by hand.

It would be nice to get that information from the noiseSFTs themselves no-questions-asked. This may remove a degree of freedom related to specify signals shorter than the actual data time span, but I'd say transient windows already cover that.

**Comment by dbkeitel** [comment]
:+1: in principle, though the transient part needs a careful look, since in some places there's some interference between the general start/endtime and the actual windowing options.

I suggest you make a draft PR when you have time, ignoring transients to start with, and I can check the effect on transients.

**Comment by dbkeitel** [comment]
After #90/#91 this should be easier since I'm disentangling the transient situation.

**Comment by dbkeitel** [comment]
> +1 in principle, though the transient part needs a careful look, since in some places there's some interference between the general start/endtime and the actual windowing options.
> 
> I suggest you make a draft PR when you have time, ignoring transients to start with, and I can check the effect on transients.

After #91 the interference with transients should be gone, so this could be quite easy to do now.
