### ISSUE TITLE
Test BSGL thoroughly

### ISSUE THREAD

**Issue by Rodrigo-Tenorio** [PyFstat/PyFstat#99]
Lately, some developments may have broken BSGL-related features (see e.g. #98 ). 

Actual numerical checks on BSGL should be implemented,  since there's only one "sanity" test [here](https://github.com/PyFstat/PyFstat/blob/master/tests.py#L550) which only checks if the value is positive.

- [ ] Implement numerical tests for BSGL statistic

**Comment by dbkeitel** [comment]
I'm adding one more simple test in #100, but to do this properly the best would be to reproduce part or all of lalpulsar's [LineRobustStatsTest.c](https://git.ligo.org/lscsoft/lalsuite/-/blob/master/lalpulsar/test/LineRobustStatsTest.c) and maybe some bits from [testHierarchSearchGCT.sh](https://git.ligo.org/lscsoft/lalsuite/-/blob/master/lalapps/src/pulsar/GCT/testHierarchSearchGCT.sh) too.

**Comment by dbkeitel** [comment]
> I'm adding one more simple test in #100, but to do this properly the best would be to reproduce part or all of lalpulsar's [LineRobustStatsTest.c](https://git.ligo.org/lscsoft/lalsuite/-/blob/master/lalpulsar/test/LineRobustStatsTest.c) and maybe some bits from [testHierarchSearchGCT.sh](https://git.ligo.org/lscsoft/lalsuite/-/blob/master/lalapps/src/pulsar/GCT/testHierarchSearchGCT.sh) too.

Directly reproducing those lalsuite tests doesn't make sense, as we're just wrapping the lalpulsar function anyway. #245 adds some basic qualitative test cases instead.

**Comment by dbkeitel** [comment]
Should be in a decent enough state for now. Any more detailed tests probably only make sense after/if implementing more direct tuning options in #260.
